[skse64]
filename = Skyrim Script Extender (SKSE64) Steam 30379 2.3.1 2026-08-27T16-52Z s6Og0dG94.7z

[address_library]
filename = Address Library All in One (1.7.104.0) v13 32444 13 2026-08-27T15-29Z Ae46W7Fw2.zip

[powerofthree_tweaks]
filename = powerofthrees Tweaks 51073 1.17.1 2026-08-25T00-11Z zYsEpQvXg.7z

[ussep]
filename = Unofficial Skyrim Special Edition Patch 266 4.3.9c 2026-09-05T22-22Z lNkz9LChN.7z

[achievements_mods_enabler]
filename = Achievements Mods Enabler SE-AE-245-1-41-1715217907.zip

[alternate_start]
filename = Alternate Start - Live Another Life-272-4-2-6a-1772996477.7z

[skyui]
filename = SkyUI-12604-6-11-1778020881.zip
